
apiVersion: v1
kind: Service
metadata:
  name: webhook-service
  namespace: keto
spec:
  ports:
    - port: 443
      targetPort: 443
  selector:
    app.kubernetes.io/name: keto-maester
    app.kubernetes.io/instance: keto
